"""add confidence rating

Revision ID: 25036b0521fe
Revises: 2fe825d41688
Create Date: 2026-08-03 12:48:27.063959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25036b0521fe'
down_revision: Union[str, Sequence[str], None] = '2fe825d41688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_analysis', sa.Column('confidence', sa.Integer(), nullable=False))
    op.add_column('review_analysis', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_analysis', 'rating')
    op.drop_column('review_analysis', 'confidence')
    # ### end Alembic commands ###
